version: '3.8'

services:
  notebook:
    build:
      context: .
      dockerfile: ./srv/Dockerfile
    init: true
    restart: unless-stopped
    ports:
      - "80:8888"
    command:
      /bin/bash -c "/opt/conda/bin/conda install jupyter -y --quiet && /opt/conda/bin/jupyter notebook --notebook-dir=/opt/notebooks --ip='0.0.0.0' --port=8888 --no-browser --allow-root"
    tty: true
    volumes:
       - ./notebooks:/opt/notebooks
